import Container from "../components/Container";
import ErrorMessage from "../components/ErrorMessage";
import Head from "next/head";
import UserList from "../components/UserList";
import axios, { AxiosError } from "axios";
import parseLinkHeader from "parse-link-header";
import { useQuery } from "react-query";
import { useState } from "react";
import type { GitHubAPIErrorBody } from "../utils/types";
import type { GitHubUser } from "../components/UserListItem";
import type { NextPage } from "next";

type QueryData = { data: GitHubUser[]; next?: string };

const Home: NextPage = () => {
  const [since, setSince] = useState("0");
  const {
    isLoading,
    isError,
    data: queryData,
    error,
  } = useQuery<QueryData, AxiosError<GitHubAPIErrorBody>>(
    ["users", since],
    () =>
      axios
        .get("https://api.github.com/users", {
          params: {
            per_page: "20",
            since,
          },
        })
        .then((res) => {
          const linkHeader = parseLinkHeader(res.headers.link);

          return {
            data: res.data,
            next: linkHeader?.next?.since,
          };
        }),
    { refetchOnWindowFocus: false }
  );

  const { data, next } = queryData || {};

  return (
    <Container>
      <Head>
        <title>Access Frontend Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Access Frontend Exercise</h1>
      {isLoading && <h1>🔄</h1>}
      {isError && error && <ErrorMessage error={error} />}

      {data && (
        <>
          <div>Items on this page: {data.length}</div>
          <div>
            ID on this page: {data[0].id} ~ {data[data.length - 1].id}
          </div>
          {next && (
            <div>
              <button
                onClick={() => {
                  setSince(next);
                }}
              >
                ▶
              </button>
            </div>
          )}
          <UserList users={data}></UserList>
        </>
      )}
    </Container>
  );
};

export default Home;
